acti: relu
alpha: 0.9
backbone: resnet101
batch: 512
beta1: 0.9
beta2: 0.999
checkpoint: null
coco_adj: ./data/mscoco/coco_adj.pkl
coco_glove: ./data/mscoco/coco_glove_word2vec.pkl
coco_root: ./data/mscoco
coco_unseen: ./data/mscoco/unseen_classes.txt
data: "coco"
decay_mode: null
epoch: 100
grad_clip: null
learning_rate: 0.0005
lr_decay: 0.5
log_step: 100
loss: "rank"
model: "fast0tag"
n_val_img: 0
n_worker: 2
nuswide_root: /media/hehuang/Data/nus_wide
optimizer: adam
result: ./result
save_epoch: 0
seed: 42
exp_name: "fast0tag-eng"
eval_all: true
