acti: relu
alpha: 0.9
backbone: resnet101
batch: 128
beta1: 0.9
beta2: 0.999
checkpoint: null
coco_adj: ./data/mscoco/coco_adj.pkl
coco_glove: ./data/mscoco/coco_glove_word2vec.pkl
coco_root: /media/hehuang/Data/coco
coco_unseen: ./data/mscoco/unseen_classes.txt
coco_seen_val: ./data/mscoco/seen_val_classes.txt
config: null
d_dim: 512
data: nuswide81
decay: 0.0
decay_epoch: 10
decay_mode: loss
dropout: 0.0
epoch: 200
fin_layers: '512'
fout_layers: ''
frel_layers: '200'
gamma: 0.001
gcn_layers: 256 256 128 128
grad_clip: 10.0
h_dim: 1024
imgnet_meta: ./data/meta_data.pkl
learning_rate: 0.001
log_step: 100
lr_decay: 0.5
model: rgcn
n_neg: 5
n_val_class: 0
n_val_img: 0
n_worker: 3
nuswide_root: /media/hehuang/Data/nus_wide
optimizer: adam
patience: 5
pos_bias: true
pos_fuse: cat
result: ./result
save_epoch: 0
seed: 42
setting: trans_image
sparse: false
t_max: 4
tune_pos: true
use_attn: false
use_imgnet: true
word_dim: 300
wup_neg: 0.11
wup_pos: 0.5
enc_layers: '256'
dec_layers: '256'
wVAE: 1.0
exp_name: 'gcn-posVAE-nus'
self_cyc: True
normalize: False

