acti: relu
alpha: 0.9
backbone: resnet101
batch: 256
beta1: 0.9
beta2: 0.999
checkpoint: null
coco_glove: ./data/mscoco/coco_glove_word2vec.pkl
coco_root: ./data/mscoco
coco_unseen: ./data/mscoco/unseen_classes.txt
coco_seen_val: ./data/mscoco/seen_val_classes.txt
config: null
d_dim: 10
data: vg
decay: 0.0
decay_mode: null
dropout: 0.0
exp_name: 'ggnn-base'
epoch: 200
fin_layers: '512 128'
fout_layers: ''
frel_layers: '256'
gcn_layers: 1024 512
grad_clip: 10.0
h_dim: 1024
imgnet_meta: ./data/meta_data.pkl
learning_rate: 0.0001
log_step: 100
lr_decay: 0.5
model: ggnn
n_neg: 5
n_val_class: 0
n_val_img: 0
n_worker: 3
nuswide_root: /media/hehuang/Data/nus_wide
optimizer: rmsprop
patience: 5
pos_bias: true
pos_fuse: cat
result: ./result
save_epoch: 0
seed: 42
setting: trans_image
sparse: false
t_max: 4
tune_pos: true
use_attn: false
use_imgnet: false
word_dim: 300
wup_neg: 0.11
wup_pos: 0.3
enc_layers: '256'
dec_layers: '256'
wVAE: 1.0
vg_root: '/media/hehuang/Data/visual_genome'
vg_anno: './data/visual_genome/objects.json'
vg_unseen: './data/visual_genome/vg_unseen_classes.txt'
