acti: relu
alpha: 0.9
backbone: resnet101
batch: 512
beta1: 0.9
beta2: 0.999
checkpoint: null
coco_glove: ./data/mscoco/coco_glove_word2vec.pkl
coco_root: ./data/mscoco
coco_unseen: ./data/mscoco/unseen_classes.txt
coco_seen_val: ./data/mscoco/seen_val_classes.txt
config: null
data: "coco"
d_dim: 10
epoch: 100
grad_clip: 10.0
learning_rate: 0.0001
lr_decay: 0.5
log_step: 100
loss: "rank"
model: skg
n_val_img: 0
n_worker: 2
nuswide_root: /media/hehuang/Data/nus_wide
optimizer: adam
result: ./result
save_epoch: 0
seed: 42
t_max: 5
wup_neg: 0.11
wup_pos: 0.5
exp_name: "skg"
sparse: false
use_attn: false
use_imgnet: false
word_dim: 300
decay_mode: null
patience: 3
vg_K: 100
vg_root: '/media/hehuang/Data/visual_genome'
vg_anno: './data/visual_genome/objects.json'
vg_unseen: './data/visual_genome/vg_unseen_classes2.txt'
